# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'init script' # runs during prebuild
    command: echo 'start script'
  - name: Install JDK
    command: sdk install java 18-amzn
  - name: Pull Redis Stack Docker image
    command: docker pull redis/redis-stack-server:latest

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 6379
    onOpen: open-preview
