# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'init script' # runs during prebuild
    command: sdk install java 17.0.1.12.1-amzn < /dev/null && sudo apt-get --assume-yes install redis-server && docker pull redislabs/redismod:latest
  - command: |
      gp open README.md
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 6379
    onOpen: ignore
    visibility: public
  - port: 8080
    onOpen: ignore
    visibility: public
vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-pack
    - pivotal.vscode-spring-boot
    - gabrielbb.vscode-lombok
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - vscjava.vscode-maven