# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Dependencies
    init: |
      sdk install java 18-amzn
      docker pull redis/redis-stack-server:latest

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 6379
    onOpen: open-preview
