# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Dependencies
    init: |
      sdk install java 18-amzn < /dev/null
      docker pull redis/redis-stack-server:latest
  - name: Open README
    command: |
      gp open README.md
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 6379
  - port: 8080
    onOpen: open-preview
